rango/urls.py
from django.urls import path
from rango import views

app_name = "rango"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("category/<slug:category_name_slug>/", views.show_category, name="show_category"),
    path("add_category", views.add_category, name="add_category"),
    path("category/<slug:category_name_slug>/add_page/", views.add_page, name="add_page"),
    path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("restricted/", views.restricted, name="restricted"),
    path("logout/", views.user_logout, name="logout"),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

from django.urls import path
from django.urls import include
from rango import views

urlpatterns = [
                  path("", views.index, name="index"),
                  path("rango/", include("rango.urls")),
                  # The above maps any URLs starting with rango/ to be handled by rango
                  path("admin/", admin.site.urls),
                  path("rango/about/", views.about, name="about")  # creates new about page
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

rango/models.py
from django.db import models

from django.template.defaultfilters import slugify

from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):  # save method is always called when creating or updating an instance of Django
        # model
        self.slug = slugify(self.name)  # slugify creates a url safe name by removing the spaces for dashes
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # this line is required. links user profile to a user model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_images", blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category

from django.contrib.auth.models import User
from rango.models import UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form
    class Meta:
        # provides a association between a ModelForm and a model
        model = Category
        fields = ("name",)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page. ")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page. ")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # provides an association between ModelForm and a model
        model = Page

        # what fields do we want to include in our form ?
        # This way we don't need every field in the model present
        # Some fields may allow NULL values, we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form
        exclude = ("category",)
        # or specify the fields to include (don't include the category field)
        # fields = ("title", "url", "views")

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get("url")

        # If url is not empty and doesnt start with "http://"
        # then prepend "http://"
        if url and not url.startswith("http://"):
            url = f"http://{url}"
            cleaned_data["url"] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password")


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("website", "picture")

rango/views.py
from django.shortcuts import render

from django.http import HttpResponse

# Import the Category Model
from rango.models import Category

from rango.models import Page

# For the forms
from rango.forms import CategoryForm
from rango.forms import PageForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required
from datetime import datetime


def index(request):
    # Constructs a dictiobjectsonary to pass to the template engine as its context
    # Note the key boldmessage matches to {{boldmessage}} in the template!
    category_list = Category.objects.order_by("-likes")[:5]
    page_list = Page.objects.order_by("-views")[:5]

    context_dict = {"boldmessage": "Crunchy, creamy, cookie, candy, cupcake!",
                    "categories": category_list,
                    "pages": page_list,
                    }

    visitor_cookie_handler(request)
    # obtain our response object early so we can add cookie info
    response = render(request, "rango/index.html", context=context_dict)

    # return response back to the user updating any cookies that need changed
    return response


def about(request):
    context_dict = {"boldmessage": "Hey I'm not rango I'm about"}

    # this is to test the cookie
    visitor_cookie_handler(request)
    context_dict["visits"] = request.session["visits"]

    return render(request, "rango/about.html", context=context_dict)


def show_category(request, category_name_slug):
    # create a context dict which we can pass to the template rendering engine
    context_dict = {}

    try:
        # checks to see if category name slug exists with this given name
        # .get() method return one model instance or raisers an exception
        category = Category.objects.get(slug=category_name_slug)

        # retrieves all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)

        # adds our result list to the template context under name pages.
        context_dict["pages"] = pages
        # we also add the category object from the database to the context dict
        # We'll use this in the template to verify that the category exists.
        context_dict["category"] = category
    except Category.DoesNotExist:
        # we get here if we didnt find any specified category
        # dont do anything - the template will display the "no category message for us"
        context_dict["category"] = None
        context_dict["pages"] = None

    # go render the response and return it to the client
    return render(request, "rango/category.html", context=context_dict)


def add_category(request):
    if request.user.is_authenticated:
        form = CategoryForm()

        # A HTTP post ?
        if request.method == "POST":
            form = CategoryForm(request.POST)

            # have we been provided with a valid form ?
            if form.is_valid():
                # save new category in database.
                form.save(commit=True)
                # Now that the category is saved we confirm this.
                # for now just redirect the user back to the index view.
                return redirect("/rango/")
            else:
                # The supplied form contains errors
                print(form.errors)

        # Will handle the bad form, new form, or no form supplied case
        # render the form with error message (if any)
        return render(request, "rango/add_category.html", {"form": form})
    else:
        return redirect(reverse('rango:login'))


def add_page(request, category_name_slug):
    if request.user.is_authenticated:
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None

        # You can not add a page to a Category that does not exist....
        if category is None:
            return redirect("/rango/")

        form = PageForm()

        if request.method == "POST":
            form = PageForm(request.POST)

            if form.is_valid():
                if category:
                    page = form.save(commit=False)
                    page.category = category
                    page.views = 0
                    page.save()

                    return redirect(reverse("rango:show_category", kwargs={"category_name_slug": category_name_slug}))

            else:
                print(form.errors)

        context_dict = {"forms": form, "category": category}
        return render(request, "rango/add_page.html", context=context_dict)
    else:
        return redirect(reverse('rango:login'))


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    if request.method == "POST":
        # attempts to grab the information the raw form info
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # save the users data into the database
            user = user_form.save()

            # now we hash the password with the set_password method
            # once hashed we can update the user object
            user.set_password(user.password)
            user.save()

            # now sort out the user profile instance
            # since we need to set the user attribute ourselves
            # we set commit=False this delays saving the model
            # until we 're ready to avoid integrity problems
            profile = profile_form.save(commit=False)
            profile.user = user

            # did the user provide a profile pic
            # if so we need to get it form the input form and
            # put it the userProfile model
            if "picture" in request.FILES:
                profile.picture = request.FILES["picture"]

            # now we save the userProfile model instance
            profile.save()

            # update our variable to indicate that the template
            # registration was successful
            registered = True
        else:
            # Invalid from or forms - mistake or something else?
            # print problems to the terminal
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two MdoelForm instances
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # render the template depneding on the context
    return render(request, "rango/register.html", context={"user_form": user_form, "profile_form": profile_form,
                                                           "registered": registered})


def user_login(request):
    # if the requets is a http request try to pull out the relevant info
    if request.method == "POST":
        # gather the username and password provided by the user
        # returns None if the value does not exist.
        username = request.POST.get("username")
        password = request.POST.get("password")
        # uses Django's machinery to attempt to see if the username/password
        # combination is valid - a user object is returned if it is
        user = authenticate(username=username, password=password)

        # if we have a user object the details are correct.
        # if none pythons way of representing the absence of a value
        if user:
            # is the account active or has it been disabled
            if user.is_active:
                # if the account is valid and active we can log the user in
                # we'll send the uer back to the homepage.
                login(request, user)
                return redirect(reverse("rango:index"))
            else:
                # An inactive account was used - no logging in !
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details we're provided. so we cant log the user in
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied")
    # This scenario would most lilly be a HTTP get.
    else:
        # No context variables to pass to the template hence the
        # blank dict object
        return render(request, "rango/login.html")


@login_required
def restricted(request):
    return render(request, "rango/restricted.html")


@login_required
def user_logout(request):
    # since we know the user is logged in we can just log them out
    logout(request)
    # take the user back to the homepage
    return redirect(reverse("rango:index"))


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, "visits", "1"))

    last_visit_cookie = get_server_side_cookie(request, "last_visit", str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")

    # if its been more than a day since the last visit...
    if(datetime.now() - last_visit_time).days > 0:
        visits += 1
        # Update the last visit cookie now that we have updated the count _
        request.session["last_visit"] = str(datetime.now())
    else:
        # set the last visit cookie
        request.session["last_visit"] = last_visit_cookie

    # Update/set the visits cookie
    request.session["visits"] = visits


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

templates/rango/about.html
{% extends "rango/base.html" %}
{% load staticfiles %} <!--django loads the static files -->

{% block title_block %}
About Rango
{% endblock %}

{% block body_block %}
    <h1>This is a about page</h1>
    <div>
        This is such a cool about page !!! <br />
        <strong>{{boldmessage}}</strong> <br />
    </div>
    <div>
        <a href="{% url "rango:index" %}">Home</a>
        <img src="media/d.png" alt = "This is a image of the cat !!!" />
        <p>Visits: {{ visits }}</p>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends "rango/base.html" %}
{% load staticfiles %} <!--django loads the static files -->

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    {% if user.is_authenticated %}
        <div>
            <form id="category_form" method="post" action="{% url "rango:add_category" %}">
                {% csrf_token %}
                <!--The first for loop controls hidden elements the second visible elements -->
                {% for hidden in form.hidden_fields %}
                    {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category" />
            </form>
        {% if category %}
        <a href="{% url 'rango:add_category' category.slug %}">Add Category</a> <br/>
        {% else %}
            The specified category does not exist.
        {% endif %}
        </div>
    {% else %}
        Only user that have logged in can add categories.
    {% endif %}
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% load staticfiles %} <!--django loads the static files -->

{% block title_block %}
Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page</h1>
    <div>
        <form id="category_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            <!--The first for loop controls hidden elements the second visible elements -->
            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page">
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
<head lang="en">
    <title>Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'rango:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
            <li><a href="{% url 'rango:login' %}">Login</a></li>
        {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

templates/rango/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
            <a href="{% url "rango:show_category" c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
            <a href="{% url "rango:show_category" c.slug %}">{{ c.name }}</a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/rango/category.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
         {% for page in pages %}
         <li><a href="{{ page.url }}"> {{page.title}}</a></li>
         {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url "rango:add_page" category.slug %}">Add Pages</a><br />
        {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends "rango/base.html" %}
{% load staticfiles %} <!--django loads the static files -->

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
    {% if user.is_authenticated %}
        howdy {{ user.username }}!
    {% else %}
        hey there partner!
    {% endif %}
        <strong>{{boldmessage}}</strong> <br />
    </div>

    <h2>Most Liked Categories</h2>
    <div>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li>
                <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
    </div>

    <!--Displays most viewed pages  -->
    <h2>Most Viewed Pages</h2>
    <div>
     {% if pages %}
        <ul>
        {% for page in pages %}
            <li>
                <a href="{{ page.url }}"> {{ page.title}}</a>
            </li>
        {% endfor %}
        </ul>
     {% else %}
        <strong>There are no pages present.</strong>
     {% endif %}
    </div>

    <div>
        <a href="{% url "rango:about" %}">About</a><br />
        <img src="{% static "images/rango.jpg"%}" alt = "Picture of Rango" />
    </div>
{% endblock %}

templates/rango/login.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url "rango:login" %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/register.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
    Rango says: <strong>thank you for registering!</strong>
    <a href="{% url "rango:index" %}">Return to the homepage.</a><br />
{% else %}
    Rango says: <strong>register here!</strong><br />
    <form id="user_form" method="post" action="{% url "rango:register" %}" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
    </form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends "rango/base.html" %}
{% load staticfiles %}

{% block title_block %}
     Restricted Page
{% endblock %}

{% block body_block %}
    This page is restricted !!!
{% endblock %}